//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_AlumniEntities : DbContext
    {
        public Project_AlumniEntities()
            : base("name=Project_AlumniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<news> news { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<reply> replies { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vacancy> vacancies { get; set; }
        public virtual DbSet<usercours> usercourses { get; set; }
    }
}
