//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int messageid { get; set; }
        public string text { get; set; }
        public int users_userid1 { get; set; }
        public int users_userid { get; set; }
        public System.DateTime date { get; set; }
        public byte[] picture { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
