//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int id { get; set; }
        public string message { get; set; }
        public int sender_id { get; set; }
        public int reciever_id { get; set; }
        public System.DateTime created_at { get; set; }
        public string status { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
