//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAlumni.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<gender> genders { get; set; }
        public virtual DbSet<picture> pictures { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<reply> replies { get; set; }
        public virtual DbSet<report> reports { get; set; }
        public virtual DbSet<tag> tags { get; set; }
        public virtual DbSet<usercours> usercourses { get; set; }
        public virtual DbSet<vacancy> vacancies { get; set; }
        public virtual DbSet<news> news { get; set; }
    }
}
