//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAlumni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int vacancies_vacancyid { get; set; }
        public int posts_postid { get; set; }
        public int reportid { get; set; }
        public string text { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual post post { get; set; }
        public virtual vacancy vacancy { get; set; }
    }
}
