//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAlumni.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usercours
    {
        public string graduationyear { get; set; }
        public int courses_courseid { get; set; }
        public string users_userid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual cours cours { get; set; }
    }
}
